<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql psycopg2-binary > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql+psycopg2://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

select CURRENT_DATE

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-10-27

In [9]:
%%sql
select *
from product

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

2517 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2513,505026,Contoso Bluetooth Active Headphones L15 Red,"Contoso, Ltd",Contoso,Red,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2513,2514,505027,Contoso Bluetooth Active Headphones L15 White,"Contoso, Ltd",Contoso,White,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2514,2515,505028,Contoso In-Line Coupler E180 White,"Contoso, Ltd",Contoso,White,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2515,2516,505029,Contoso In-Line Coupler E180 Black,"Contoso, Ltd",Contoso,Black,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2516,2517,505030,Contoso In-Line Coupler E180 Silver,"Contoso, Ltd",Contoso,Silver,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories

In [32]:
%%sql
select CURRENT_DATE,
       s.orderdate,
       p.categoryname,
       sum(s.quantity* s.netprice*s.exchangerate)
from sales s
join product p on s.productkey = p.productkey
where  extract(year from orderdate)>= EXTRACT(year from CURRENT_DATE)-5
group by s.orderdate,p.categoryname
order by s.orderdate,p.categoryname

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

     current_date   orderdate                   categoryname      sum
0      2026-10-27  2021-01-01                          Audio  1206.67
1      2026-10-27  2021-01-01        Cameras and camcorders   2228.75
2      2026-10-27  2021-01-01                    Cell phones 10582.00
3      2026-10-27  2021-01-01                      Computers 12718.95
4      2026-10-27  2021-01-01                 Games and Toys   235.53
...           ...         ...                            ...      ...
8952   2026-10-27  2024-04-20                      Computers 58353.68
8953   2026-10-27  2024-04-20                 Games and Toys  1744.30
8954   2026-10-27  2024-04-20                Home Appliances  1562.04
8955   2026-10-27  2024-04-20  Music, Movies and Audio Books  4949.43
8956   2026-10-27  2024-04-20                   TV and Video  9841.91

[8957 rows x 4 columns]

In [33]:
%%sql

select CURRENT_DATE,
       s.orderdate,
       p.categoryname,
       sum(s.quantity* s.netprice*s.exchangerate)
from sales s
join product p on s.productkey = p.productkey
where  orderdate >= CURRENT_DATE-INTERVAL'5 years'
group by s.orderdate,p.categoryname
order by s.orderdate,p.categoryname

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

6930 rows affected.

     current_date   orderdate                   categoryname      sum
0      2026-10-27  2021-10-27                          Audio  2321.99
1      2026-10-27  2021-10-27        Cameras and camcorders  10070.25
2      2026-10-27  2021-10-27                    Cell phones 20463.10
3      2026-10-27  2021-10-27                      Computers 37315.42
4      2026-10-27  2021-10-27                 Games and Toys   143.96
...           ...         ...                            ...      ...
6925   2026-10-27  2024-04-20                      Computers 58353.68
6926   2026-10-27  2024-04-20                 Games and Toys  1744.30
6927   2026-10-27  2024-04-20                Home Appliances  1562.04
6928   2026-10-27  2024-04-20  Music, Movies and Audio Books  4949.43
6929   2026-10-27  2024-04-20                   TV and Video  9841.91

[6930 rows x 4 columns]

In [37]:
%%sql

Select EXTRACT(DAY from age('2024-04-20','2024-04-10')) - 5

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  ?column?
0        5

In [61]:
%%sql
select
    Date_PART('year', orderdate) as order_year,
    ROUND(AVG(extract(days from AGE(deliverydate,orderdate))),2) as processing_time,
    cast(sum(quantity* netprice*exchangerate) as integer) as net_revenue
from sales
where  orderdate >= CURRENT_DATE-INTERVAL'5 years'
group by order_year
order by order_year

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

   order_year processing_time  net_revenue
0     2021.00            1.45      6790764
1     2022.00            1.62     44864557
2     2023.00            1.75     33108566
3     2024.00            1.67      8396527